### ISSUE TITLE
v0.0.1 Road Map

### ISSUE THREAD

**Issue by xuzijian629** [xuzijian629/tcs-graphlib#1]
- [ ] Integrate github actions for tests
- [ ] Implement a simple graph interface
- [ ] Implement a heuristic for treewidth
